### ISSUE TITLE
Including universe size in ReachPoint

### ISSUE THREAD

**Issue by amiragha** [world-federation-of-advertisers/planning-evaluation-framework#106]
https://github.com/world-federation-of-advertisers/planning-evaluation-framework/blob/49e259f70837a19b34726d9e3001d61efd1ba0f1/src/models/reach_point.py#L27

I think the concept of ReachPoint is ambiguous without defining the universe size. Including the universe size information in a ReachCurve can help keep the numerical calculation and modeling at the level of the normalized reach. It would be more helpful to work with normalized reach especially for simulation and research purposes.

Let me know what you think.

**Comment by jiayu-google** [comment]
Makes great sense to me.  Recommendations accepted.  Please have another round of review of PR105!
